#!/bin/bash

preferences="$(isabelle getenv -b ISABELLE_HOME_USER)/etc/preferences"
properties="$(isabelle getenv -b JEDIT_SETTINGS)/properties"

if [[ -z $properties || -z $preferences ]]; then 
	echo "Can't find 'isabelle' binary.
		You probably need modify your path variable."
else
  python merge-settings.py $preferences $properties
  sed -i "1s/^/(*This file was generated by set-dark.sh at $(date -I'seconds')*)\n/" new_preferences
  sed -i "1s/^/## This file was generated by set-dark.sh at $(date -I'seconds')*)\n/" new_properties
  mv new_preferences $preferences
  mv new_properties $properties
fi